version: '3'

services:
  mongo_seed:
    build: ./build_scripts
    env_file:
      - .env
    links:
      - mongo
    depends_on:
      - mongo

  daily_script:
    build: ./daily_script
    links:
      - mongo
      - webapp
    env_file:
      - .env
    depends_on:
      - mongo

  webapp:
    build: ./app
    links:
      - mongo
    ports:
      - "9898:9898"
    depends_on:
      - mongo
    env_file:
      - .env

