version: '3'

services:
  daily_script:
    build: ./daily_script
    links:
      - mongo
      - webapp
    env_file:
      - .env
    depends_on:
      - mongo

  webapp:
    build: ./app
    links:
      - mongo
    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"
    depends_on:
      - mongo
    env_file:
      - .env

